# Generated by Django 4.0.4 on 2022-04-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0003_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
